version: '3.8'
services:
  your-service-name:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DISPLAY=${DISPLAY}
    command: bash -c "cd /app && make && ./your-graphical-app"