
/**
 * @file testxPosNNCode.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2024-01-27
 **/

#include "testxPosNNCode.hpp"
#include "neural_network.hpp"
#include "robots/catoms3D/catoms3DMotionEngine.h"
#include "robots/catoms3D/catoms3DRotationEvents.h"
#include <thread>
#include <chrono>

testxPosNNCode::testxPosNNCode(Catoms3DBlock *host) : Catoms3DBlockCode(host), module(host)
{
    // @warning Do not remove block below, as a blockcode with a NULL host might be created
    //  for command line parsing
    if (not host)
        return;

    // Registers a callback (myGoFunc) to the message of type O
    addMessageEventFunc2(GO_MSG_ID,
                         std::bind(&testxPosNNCode::myGoFunc, this,
                                   std::placeholders::_1, std::placeholders::_2));

    // Registers a callback (myBackFunc) to the message of type C
    addMessageEventFunc2(BACK_MSG_ID,
                         std::bind(&testxPosNNCode::myBackFunc, this,
                                   std::placeholders::_1, std::placeholders::_2));

    // Registers a callback (myWakeupFunc) to the message of type E
    addMessageEventFunc2(WAKEUP_MSG_ID,
                         std::bind(&testxPosNNCode::myWakeupFunc, this,
                                   std::placeholders::_1, std::placeholders::_2));

    addMessageEventFunc2(ACKNOWLEDGE_MSG_ID,
                         std::bind(&testxPosNNCode::myAcknowledgeFunc,
                                   this,
                                   std::placeholders::_1,
                                   std::placeholders::_2));

    // Registers a callback (myGoFunc) to the message of type O
    addMessageEventFunc2(BROADCAST_MSG_ID,
                         std::bind(&testxPosNNCode::myBroadcastFunc, this,
                                   std::placeholders::_1, std::placeholders::_2));

    // ? set the weights of the neural network
    vector<vector<vector<double>>> weights = {{{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, 0, 1}}, {{0, 0, 0, 1}, {1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}}}; // 0 -> 2, 2 -> 4, 4 -> 6, 6 -> 0
    nn.setActivationFunction("relu");
    nn.setActivationFunctionOutput("relu");
    nn.setWeights(weights);
}

void testxPosNNCode::startup()
{
    // console << "start " << getId() << "\n";
    // console << "isInTarget" << target->isInTarget(module->position) << "\n";

    if (isLeader)
    {
        console << "start " << getId() << "\n";
        module->setColor(RED);
        // nbWaitedAnswers = sendMessageToAllNeighbors("distance", new MessageOf<int>(BROADCAST_MSG_ID, distance + 1), 1000, 100, 0);

        // move forward
        // ! be careful to use the onMotionEnd function to check if the motion is ended

        vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> motions =
          Catoms3DMotionEngine::getAllRotationsForModule(module);
        console << "motions size : " << motions.size() << "\n";
        auto motion=motions.begin();
        bool found=false;

        Cell3DPosition position = module->position;
        console << "module position : " << position << "\n";

        while (motion!=motions.end() && !found) {
            console << motion->second.pivot << "\n";
            int pivotPort = findNeighborPort((*motion).second.pivot);
            console << "pivotPort : " << pivotPort << "\n";
            console << "can move to pivotPort : " << canMove(pivotPort) << "\n";
            Cell3DPosition finalPos;

            short finalOrient;  
            (*motion).second.getFinalPositionAndOrientation(finalPos, finalOrient);
            Cell3DPosition d = finalPos - position;
            console << "finalPos : " << finalPos << "\n";
            console << "finalOrient : " << finalOrient << "\n";
            // elem.first->isOctaFace(), elem.first->getConFromID(),elem.first->getConToID(),
            console << "isOctaFace : " << (*motion).first->isOctaFace() << "\n";
            console << "getConFromID : " << (*motion).first->getConFromID() << "\n"; // same as pivotPort
            console << "getConToID : " << (*motion).first->getConToID() << "\n";
            console << "(dx, dy, dz) : " << d << "\n";

            if (pivotPort!=-1 && canMove(pivotPort)) {
                // scheduler->schedule(new Catoms3DRotationStartEvent(scheduler->now() + 1000, module, (*motion).second));
                // found=true;
            }
            motion++;
        }

        // moveToFirst();
        moveToN(0);
    }
}
void testxPosNNCode::myGoFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender)
{
    MessageOf<int> *msg = static_cast<MessageOf<int> *>(_msg.get());
    int msgData = *msg->getData();
}

void testxPosNNCode::myBackFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender)
{
    // MessageOf<int>* msg = static_cast<MessageOf<int>*>(_msg.get());
    // int msgData = *msg->getData();
}

void testxPosNNCode::myWakeupFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender)
{
}

void testxPosNNCode::myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender)
{

    // ? la fonction Acknowledge sert à retourner le message de confirmation de la réception du message broadcast

    nbWaitedAnswers--; // on diminue le nombre de messages attendus, en effet on a reçu la confirmation d'un module
    console << "rec. Ack(" << nbWaitedAnswers << ") from " << sender->getConnectedBlockId() << "";
    if (nbWaitedAnswers == 0)
    { // si on a reçu toutes les confirmations
        if (parent == nullptr)
        { // si on est le leader
            setColor(-1);
        }
        else
        { // sinon on envoie un message de confirmation au parent
            sendMessage("ack2parent", new Message(ACKNOWLEDGE_MSG_ID), parent, 1000, 100);
        }
    }
}

void testxPosNNCode::myBroadcastFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender)
{
    // no broadcast in this version
}

void testxPosNNCode::parseUserBlockElements(TiXmlElement *config)
{
    const char *attr = config->Attribute("leader");
    isLeader = (attr ? Simulator::extractBoolFromString(attr) : false);
    if (isLeader)
    {
        std::cout << getId() << " is leader!" << std::endl; // complete with your code
    }
}

void testxPosNNCode::onTap(int face)
{
    // use onTap by ctrl + right click and then select "Tap"
    std::cout << "Block 'tapped':" << getId() << std::endl; // complete with your code here
    moveToN(1);
    std::cout << "Current Position: " << module->position << std::endl;

}

void testxPosNNCode::onMotionEnd()
{
    // use onMotionEnd by ctrl + right click and then select "MotionEnd"
    moveTo++;
    std::cout << "Motion ended" << std::endl; // complete with your code here
    isMoving = false;
    numberOfMoves--;
    if (numberOfMoves > 0) { // do not move if we have reached the limit of moves
        // wait one second before moving again
        scheduler->schedule(new InterruptionEvent<int>(scheduler->now() + 1000, module, 1)); // time is in microseconds
    }
}

int testxPosNNCode::findNeighborPort(const Catoms3DBlock *neighbor) {
            int i=0;
  while (i<FCCLattice::MAX_NB_NEIGHBORS && module->getNeighborBlock(i)!=neighbor) {
            i++;
  }
  return (i<FCCLattice::MAX_NB_NEIGHBORS?i:-1);
}

bool testxPosNNCode::canMove(int port) {
    vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> motions =
            Catoms3DMotionEngine::getAllRotationsForModule(module);
   for (auto &motion:motions) {
       int pivotPort = findNeighborPort(motion.second.pivot);
       if (pivotPort==port) return true;
  }
  return false;
}

void testxPosNNCode::moveStupid() {
    vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> motions =
          Catoms3DMotionEngine::getAllRotationsForModule(module);
    auto motion=motions.begin();
    scheduler->schedule(new Catoms3DRotationStartEvent(scheduler->now() + 1000, module, (*motion).second));
}

void testxPosNNCode::moveToFirst() {
    // move to the first possible rotation
    isMoving = true;
    vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> motions =
          Catoms3DMotionEngine::getAllRotationsForModule(module);
    auto motion=motions.begin();
    bool found=false;
    while (motion!=motions.end() && !found) {
        int pivotPort = findNeighborPort((*motion).second.pivot);
        if (pivotPort!=-1 && canMove(pivotPort)) {
            scheduler->schedule(new Catoms3DRotationStartEvent(scheduler->now() + 1000, module, (*motion).second));
            found=true;
        }
        motion++;
    }
}

void testxPosNNCode::moveToN(int n) {
    // move to the nth possible rotation
    isMoving = true;
    vector<std::pair<const Catoms3DMotionRulesLink*, Catoms3DRotation>> motions =
          Catoms3DMotionEngine::getAllRotationsForModule(module);
    auto motion=motions.begin();
    int i=0;
    bool found=false;
    while (i < n) {

        if (motion==motions.end()) {
            console << "No motion found" << "\n";
            cout << "No motion found" << endl;
            return;
        }
        i++;
        motion++;
    }
    if (i==n) {
        int pivotPort = findNeighborPort((*motion).second.pivot);
        if (pivotPort!=-1 && canMove(pivotPort)) {
            scheduler->schedule(new Catoms3DRotationStartEvent(scheduler->now() + 1000, module, (*motion).second));
            found=true;
        } else {
            console << "Can't move to pivotPort : " << pivotPort << "\n";
            cout << "Can't move to pivotPort : " << pivotPort << endl;
            return;
        }
    }
}

int getMaxIndex(vector<double> output) {
    int index = 0;
    double max = output[0];
    for (int i = 1; i < output.size(); i++) {
        if (output[i] > max) {
            max = output[i];
            index = i;
        }
    }
    return index;
}

void testxPosNNCode::onInterruptionEvent(shared_ptr<Event> event) {
    std::cout << "Interruption Ended" << std::endl; // complete with your code here
    vector<double> output = nn.feedForward(previousMoves);
    console << "Output : " << output[0] << ", " << output[1] << ", " << output[2] << ", " << output[3] << "\n";

    // get the index of the maximum value
    int index = getMaxIndex(output);
    moveTo = index*2; // to get the 0, 2, 4, 6
    previousMoves = {0, 0, 0, 0};
    previousMoves[index] = 1;
    moveToN(moveTo);
}

void testxPosNNCode::onEndOfSimulation() {
    // !! the onEndOfSimulation function is called at the end of the simulation for only ONE module !!
    console << "End of simulation" << "\n";
    cout << "End of simulation" << endl;
    
    // ? so we need to get all the modules from the world
    map<bID, BaseSimulator::BuildingBlock *> modules = BaseSimulator::getWorld()->getMap();
    // get all leaders
    for (auto &elem : modules) { // ? iterate over all modules
        testxPosNNCode *blockCode = dynamic_cast<testxPosNNCode *>(elem.second->blockCode); // ? typecast the blockcode to testxPosNNCode to access the isLeader variable (and specific module data)
        if (blockCode->isLeader) { // ? check if the module is a leader
            console << "Leader Id : " << elem.first << "\n";
            cout << "Leader Id : " << elem.first << endl;
            blockCode->module->setColor(WHITE);
            console << "Final position : " << blockCode->module->position << "\n"; // ? print the final position of the leader
            cout << "Final position : " << blockCode->module->position << endl;
            console << "Module Id" << elem.first << "\n";
            cout << "Module Id" << elem.first << endl;
        }
    }
}
