
/**
 * @file C3DReconfDemoCode.hpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2024-01-27
 **/

#ifndef C3DReconfDemoCode_H_
#define C3DReconfDemoCode_H_

#include "robots/catoms3D/catoms3DSimulator.h"
#include "robots/catoms3D/catoms3DWorld.h"
#include "robots/catoms3D/catoms3DBlockCode.h"
#include "robots/catoms3D/catoms3DMotionEngine.h"
#include "robots/catoms3D/catoms3DRotationEvents.h"
static const int GO_MSG_ID = 1001;
static const int BACK_MSG_ID = 1002;
static const int WAKEUP_MSG_ID = 1003;
static const int ACKNOWLEDGE_MSG_ID = 1004;
static const int BROADCAST_MSG_ID = 1005;

using namespace Catoms3D;

class C3DReconfDemoCode : public Catoms3DBlockCode
{
private:
    Catoms3DBlock *module = nullptr;
    bool isLeader = false;
    int distance = 0;
    // int currentRound=0;
    int nbWaitedAnswers = 0;
    P2PNetworkInterface *parent = nullptr;
    bool isMoving = false;
    int numberOfMoves = 10;

public:
    C3DReconfDemoCode(Catoms3DBlock *host);
    ~C3DReconfDemoCode(){};

    /**
     * This function is called on startup of the blockCode, it can be used to perform initial
     *  configuration of the host or this instance of the program.
     * @note this can be thought of as the main function of the module
     */
    void startup() override;

    /**
     * @brief Message handler for the message 'go'
     * @param _msg Pointer to the message received by the module, requires casting
     * @param sender Connector of the module that has received the message and that is connected to the sender
     */
    void myGoFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Message handler for the message 'back'
     * @param _msg Pointer to the message received by the module, requires casting
     * @param sender Connector of the module that has received the message and that is connected to the sender
     */
    void myBackFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Message handler for the message 'wakeup'
     * @param _msg Pointer to the message received by the module, requires casting
     * @param sender Connector of the module that has received the message and that is connected to the sender
     */
    void myWakeupFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Message handler for the message `acknowledge`
     * @param _msg Pointer to the message received by the module, requires casting
     * @param sender Connector of the module that has received the message and that is connected to the sender
     */
    void myAcknowledgeFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Message handler for the message `broadcast`
     * @param _msg Pointer to the message received by the module, requires casting
     * @param sender Connector of the module that has received the message and that is connected to the sender
     */
    void myBroadcastFunc(std::shared_ptr<Message> _msg, P2PNetworkInterface *sender);

    /**
     * @brief Provides the user with a pointer to the configuration file parser, which can be used to read additional user information from each block config. Has to be overridden in the child class.
     * @param config : pointer to the TiXmlElement representing the block configuration file, all information related to concerned block have already been parsed
     *
     */
    void parseUserBlockElements(TiXmlElement *config) override;

    /**
      * @brief This function is called when a module is tapped by the user. Prints a message to the console by default.
         Can be overloaded in the user blockCode
      * @param face face that has been tapped
      */
    void onTap(int face) override;

    void onMotionEnd() override;

    int findNeighborPort(const Catoms3DBlock *neighbor);

    bool canMove(int port);

    void moveStupid();

    void moveToFirst();

    /*****************************************************************************/
    /** needed to associate code to module                                      **/
    static BlockCode *buildNewBlockCode(BuildingBlock *host)
    {
        return (new C3DReconfDemoCode((Catoms3DBlock *)host));
    }
    /*****************************************************************************/
};

#endif /* C3DReconfDemoCode_H_ */